# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-15 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='nombre',
            new_name='title',
        ),
        migrations.AddField(
            model_name='citas',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Domicilio',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='Email',
            field=models.CharField(max_length=300),
        ),
    ]
