# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-16 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171016_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
