# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-16 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20171016_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='area',
            field=models.CharField(blank=True, max_length=300, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
