# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171016_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='medico',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='citas',
            name='paciente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
