# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='medico',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Medicos'),
        ),
    ]
