# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171016_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='area',
            field=models.ForeignKey(blank=True, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='app.Area'),
        ),
    ]
