# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_control'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='apellido',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='foto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
