# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171027_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='apellido',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='medicos',
            name='foto',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='medicos',
            name='nombre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
