# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='citas',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Citas'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='consulta',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Consulta'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='control',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Control'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='evaluacion',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Evaluacion'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tratamiento',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tratamiento'),
        ),
    ]
