# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20171027_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='titulo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
