# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_prospecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='foto',
            field=models.FileField(upload_to='static'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='foto',
            field=models.FileField(upload_to='static'),
        ),
    ]
