# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20171109_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
