# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_pacientes_nacimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientes',
            old_name='Celular',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Ciudad',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Domicilio',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Referenciado',
            new_name='referenciado',
        ),
        migrations.RenameField(
            model_name='pacientes',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
