# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20171109_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='tratamiento',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tratamiento'),
        ),
    ]
